---
abstract: 'assertions support for perls >= 5.8.1'
author:
  - 'Sergey Aleynikov <randir@cpan.org>'
distribution_type: module
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-Assert
no_index:
  directory:
    - inc
    - t
    - lib/Devel/Assert
requires:
  Devel::Declare: 0.006003
  perl: 5.8.1
  Devel::StackTrace: 1.25
  Data::Printer: 0.17
  PadWalker: 1.92
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
